// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: waveshare

#ifndef _WAVESHARE_UI_H
#define _WAVESHARE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_background_png);    // assets/background.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_power_switch_png);    // assets/power_switch.png
LV_IMG_DECLARE(ui_img_cold_mode_png);    // assets/cold_mode.png
LV_IMG_DECLARE(ui_img_increase_png);    // assets/increase.png
LV_IMG_DECLARE(ui_img_decrease_png);    // assets/decrease.png
LV_IMG_DECLARE(ui_img_mode_png);    // assets/mode.png
LV_IMG_DECLARE(ui_img_airflow_png);    // assets/airflow.png
LV_IMG_DECLARE(ui_img_wind_direction_png);    // assets/wind_direction.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_background_without_circle_png);    // assets/background_without_circle.png
LV_IMG_DECLARE(ui_img_mode_cold_png);    // assets/mode_cold.png
LV_IMG_DECLARE(ui_img_mode_sleep_png);    // assets/mode_sleep.png
LV_IMG_DECLARE(ui_img_mode_dry_png);    // assets/mode_dry.png
LV_IMG_DECLARE(ui_img_mode_warm_png);    // assets/mode_warm.png
LV_IMG_DECLARE(ui_img_mode_wind_png);    // assets/mode_wind.png
LV_IMG_DECLARE(ui_img_mode_auto_png);    // assets/mode_auto.png
LV_IMG_DECLARE(ui_img_airflow_small_png);    // assets/airflow_small.png
LV_IMG_DECLARE(ui_img_airflow_middle_png);    // assets/airflow_middle.png
LV_IMG_DECLARE(ui_img_airflow_large_png);    // assets/airflow_large.png
LV_IMG_DECLARE(ui_img_decrease_white_png);    // assets/decrease_white.png
LV_IMG_DECLARE(ui_img_increase_white_png);    // assets/increase_white.png

// FONTS
LV_FONT_DECLARE(ui_font_micross100);
LV_FONT_DECLARE(ui_font_micross50);
LV_FONT_DECLARE(ui_font_simhei30);
LV_FONT_DECLARE(ui_font_simhei36);
LV_FONT_DECLARE(ui_font_simhei24);
LV_FONT_DECLARE(ui_font_simhei46);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
