// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: waveshare

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Container13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Container14 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Container19 = NULL;
lv_obj_t * ui_Container21 = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Container23 = NULL;
lv_obj_t * ui_Image19 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Container24 = NULL;
lv_obj_t * ui_Image20 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Container28 = NULL;
lv_obj_t * ui_Container25 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Container26 = NULL;
lv_obj_t * ui_Container22 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Container30 = NULL;
lv_obj_t * ui_Container27 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Container32 = NULL;
lv_obj_t * ui_Container29 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Container34 = NULL;
lv_obj_t * ui_Container31 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Container48 = NULL;
lv_obj_t * ui_Container33 = NULL;
lv_obj_t * ui_Container38 = NULL;
lv_obj_t * ui_Container42 = NULL;
lv_obj_t * ui_Container43 = NULL;
lv_obj_t * ui_Container44 = NULL;
lv_obj_t * ui_Container45 = NULL;
lv_obj_t * ui_Container36 = NULL;
lv_obj_t * ui_Container39 = NULL;
lv_obj_t * ui_Container40 = NULL;
lv_obj_t * ui_Container35 = NULL;
lv_obj_t * ui_Container37 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Switch3 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Container58 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_Container46 = NULL;
lv_obj_t * ui_Container41 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_Container47 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_Container50 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Switch5 = NULL;
lv_obj_t * ui_Container20 = NULL;
lv_obj_t * ui_Container15 = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Container16 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Container17 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Container18 = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Label15 = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Screen2, &ui_img_background_without_circle_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_height(ui_Container13, 50);
    lv_obj_set_width(ui_Container13, lv_pct(100));
    lv_obj_set_align(ui_Container13, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 15);
    lv_obj_set_y(ui_Label14, 0);
    lv_obj_set_align(ui_Label14, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label14, "08:00");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image12 = lv_image_create(ui_Container13);
    lv_image_set_src(ui_Image12, &ui_img_wifi_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image12, 100);
    lv_obj_set_y(ui_Image12, 0);
    lv_obj_set_align(ui_Image12, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container14 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 50);
    lv_obj_set_height(ui_Container14, 50);
    lv_obj_set_x(ui_Container14, 30);
    lv_obj_set_y(ui_Container14, 60);
    lv_obj_remove_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_image_create(ui_Container14);
    lv_image_set_src(ui_Image13, &ui_img_back_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container19 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container19);
    lv_obj_set_width(ui_Container19, 600);
    lv_obj_set_height(ui_Container19, 420);
    lv_obj_set_x(ui_Container19, 0);
    lv_obj_set_y(ui_Container19, 130);
    lv_obj_set_align(ui_Container19, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Container19, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Container19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container21 = lv_obj_create(ui_Container19);
    lv_obj_remove_style_all(ui_Container21);
    lv_obj_set_width(ui_Container21, 160);
    lv_obj_set_height(ui_Container21, 115);
    lv_obj_set_x(ui_Container21, -190);
    lv_obj_set_y(ui_Container21, 20);
    lv_obj_set_align(ui_Container21, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Container21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container21, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container21, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image16 = lv_image_create(ui_Container21);
    lv_image_set_src(ui_Image16, &ui_img_mode_cold_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image16, 0);
    lv_obj_set_y(ui_Image16, -20);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_Container21);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 0);
    lv_obj_set_y(ui_Label16, 26);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "清爽制冷");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_simhei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container23 = lv_obj_create(ui_Container19);
    lv_obj_remove_style_all(ui_Container23);
    lv_obj_set_width(ui_Container23, 160);
    lv_obj_set_height(ui_Container23, 115);
    lv_obj_set_x(ui_Container23, 0);
    lv_obj_set_y(ui_Container23, 20);
    lv_obj_set_align(ui_Container23, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Container23, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container23, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container23, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image19 = lv_image_create(ui_Container23);
    lv_image_set_src(ui_Image19, &ui_img_mode_sleep_png);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image19, 0);
    lv_obj_set_y(ui_Image19, -20);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_Container23);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 0);
    lv_obj_set_y(ui_Label19, 26);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "贴心睡眠");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &ui_font_simhei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container24 = lv_obj_create(ui_Container19);
    lv_obj_remove_style_all(ui_Container24);
    lv_obj_set_width(ui_Container24, 160);
    lv_obj_set_height(ui_Container24, 115);
    lv_obj_set_x(ui_Container24, 190);
    lv_obj_set_y(ui_Container24, 20);
    lv_obj_set_align(ui_Container24, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Container24, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container24, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container24, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image20 = lv_image_create(ui_Container24);
    lv_image_set_src(ui_Image20, &ui_img_mode_dry_png);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image20, 0);
    lv_obj_set_y(ui_Image20, -20);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_Container24);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 0);
    lv_obj_set_y(ui_Label20, 26);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "自动除湿");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &ui_font_simhei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container28 = lv_obj_create(ui_Container19);
    lv_obj_remove_style_all(ui_Container28);
    lv_obj_set_width(ui_Container28, 120);
    lv_obj_set_height(ui_Container28, 115);
    lv_obj_set_x(ui_Container28, -210);
    lv_obj_set_y(ui_Container28, 160);
    lv_obj_set_align(ui_Container28, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Container28, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container28, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container28, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container25 = lv_obj_create(ui_Container28);
    lv_obj_remove_style_all(ui_Container25);
    lv_obj_set_width(ui_Container25, 36);
    lv_obj_set_height(ui_Container25, 36);
    lv_obj_set_x(ui_Container25, 0);
    lv_obj_set_y(ui_Container25, -20);
    lv_obj_set_align(ui_Container25, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container25, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Container25, &ui_img_mode_cold_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Container28);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 0);
    lv_obj_set_y(ui_Label21, 26);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "制冷");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &ui_font_simhei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container26 = lv_obj_create(ui_Container19);
    lv_obj_remove_style_all(ui_Container26);
    lv_obj_set_width(ui_Container26, 120);
    lv_obj_set_height(ui_Container26, 115);
    lv_obj_set_x(ui_Container26, -70);
    lv_obj_set_y(ui_Container26, 160);
    lv_obj_set_align(ui_Container26, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Container26, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container26, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container26, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container26, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container26, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container22 = lv_obj_create(ui_Container26);
    lv_obj_remove_style_all(ui_Container22);
    lv_obj_set_width(ui_Container22, 36);
    lv_obj_set_height(ui_Container22, 36);
    lv_obj_set_x(ui_Container22, 0);
    lv_obj_set_y(ui_Container22, -20);
    lv_obj_set_align(ui_Container22, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Container22, &ui_img_mode_warm_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Container22, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Container26);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 0);
    lv_obj_set_y(ui_Label22, 26);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "制热");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &ui_font_simhei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container30 = lv_obj_create(ui_Container19);
    lv_obj_remove_style_all(ui_Container30);
    lv_obj_set_width(ui_Container30, 120);
    lv_obj_set_height(ui_Container30, 115);
    lv_obj_set_x(ui_Container30, 70);
    lv_obj_set_y(ui_Container30, 160);
    lv_obj_set_align(ui_Container30, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Container30, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container30, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container30, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container30, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container27 = lv_obj_create(ui_Container30);
    lv_obj_remove_style_all(ui_Container27);
    lv_obj_set_width(ui_Container27, 36);
    lv_obj_set_height(ui_Container27, 36);
    lv_obj_set_x(ui_Container27, 0);
    lv_obj_set_y(ui_Container27, -20);
    lv_obj_set_align(ui_Container27, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container27, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Container27, &ui_img_mode_wind_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Container30);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 0);
    lv_obj_set_y(ui_Label23, 26);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "送风");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &ui_font_simhei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container32 = lv_obj_create(ui_Container19);
    lv_obj_remove_style_all(ui_Container32);
    lv_obj_set_width(ui_Container32, 120);
    lv_obj_set_height(ui_Container32, 115);
    lv_obj_set_x(ui_Container32, 210);
    lv_obj_set_y(ui_Container32, 160);
    lv_obj_set_align(ui_Container32, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Container32, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container32, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container32, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container32, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container32, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container29 = lv_obj_create(ui_Container32);
    lv_obj_remove_style_all(ui_Container29);
    lv_obj_set_width(ui_Container29, 36);
    lv_obj_set_height(ui_Container29, 36);
    lv_obj_set_x(ui_Container29, 0);
    lv_obj_set_y(ui_Container29, -20);
    lv_obj_set_align(ui_Container29, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container29, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Container29, &ui_img_mode_dry_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Container29, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Container32);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 0);
    lv_obj_set_y(ui_Label24, 26);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "除湿");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &ui_font_simhei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container34 = lv_obj_create(ui_Container19);
    lv_obj_remove_style_all(ui_Container34);
    lv_obj_set_width(ui_Container34, 120);
    lv_obj_set_height(ui_Container34, 115);
    lv_obj_set_x(ui_Container34, -210);
    lv_obj_set_y(ui_Container34, 300);
    lv_obj_set_align(ui_Container34, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Container34, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container34, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container34, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container34, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container34, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container31 = lv_obj_create(ui_Container34);
    lv_obj_remove_style_all(ui_Container31);
    lv_obj_set_width(ui_Container31, 36);
    lv_obj_set_height(ui_Container31, 36);
    lv_obj_set_x(ui_Container31, 0);
    lv_obj_set_y(ui_Container31, -20);
    lv_obj_set_align(ui_Container31, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container31, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Container31, &ui_img_mode_auto_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Container31, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Container34);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 0);
    lv_obj_set_y(ui_Label25, 26);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "自动");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &ui_font_simhei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container48 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container48);
    lv_obj_set_width(ui_Container48, 640);
    lv_obj_set_height(ui_Container48, 420);
    lv_obj_set_x(ui_Container48, 0);
    lv_obj_set_y(ui_Container48, 130);
    lv_obj_set_align(ui_Container48, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Container48, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Container48, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container33 = lv_obj_create(ui_Container48);
    lv_obj_remove_style_all(ui_Container33);
    lv_obj_set_width(ui_Container33, 420);
    lv_obj_set_height(ui_Container33, 300);
    lv_obj_set_x(ui_Container33, 0);
    lv_obj_set_y(ui_Container33, 30);
    lv_obj_set_align(ui_Container33, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Container33, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container38 = lv_obj_create(ui_Container33);
    lv_obj_remove_style_all(ui_Container38);
    lv_obj_set_width(ui_Container38, 60);
    lv_obj_set_height(ui_Container38, 50);
    lv_obj_set_x(ui_Container38, -160);
    lv_obj_set_y(ui_Container38, -100);
    lv_obj_set_align(ui_Container38, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Container38, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container38, lv_color_hex(0xBCFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container42 = lv_obj_create(ui_Container33);
    lv_obj_remove_style_all(ui_Container42);
    lv_obj_set_width(ui_Container42, 60);
    lv_obj_set_height(ui_Container42, 80);
    lv_obj_set_x(ui_Container42, -78);
    lv_obj_set_y(ui_Container42, -100);
    lv_obj_set_align(ui_Container42, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Container42, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container42, lv_color_hex(0xBCFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container42, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container43 = lv_obj_create(ui_Container33);
    lv_obj_remove_style_all(ui_Container43);
    lv_obj_set_width(ui_Container43, 60);
    lv_obj_set_height(ui_Container43, 110);
    lv_obj_set_x(ui_Container43, 0);
    lv_obj_set_y(ui_Container43, -100);
    lv_obj_set_align(ui_Container43, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Container43, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container43, lv_color_hex(0xBCFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container43, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container44 = lv_obj_create(ui_Container33);
    lv_obj_remove_style_all(ui_Container44);
    lv_obj_set_width(ui_Container44, 60);
    lv_obj_set_height(ui_Container44, 140);
    lv_obj_set_x(ui_Container44, 80);
    lv_obj_set_y(ui_Container44, -100);
    lv_obj_set_align(ui_Container44, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Container44, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container44, lv_color_hex(0xBCFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container44, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container45 = lv_obj_create(ui_Container33);
    lv_obj_remove_style_all(ui_Container45);
    lv_obj_set_width(ui_Container45, 60);
    lv_obj_set_height(ui_Container45, 170);
    lv_obj_set_x(ui_Container45, 160);
    lv_obj_set_y(ui_Container45, -100);
    lv_obj_set_align(ui_Container45, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Container45, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container45, lv_color_hex(0xBCFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container45, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container36 = lv_obj_create(ui_Container33);
    lv_obj_remove_style_all(ui_Container36);
    lv_obj_set_width(ui_Container36, 40);
    lv_obj_set_height(ui_Container36, 40);
    lv_obj_set_x(ui_Container36, -160);
    lv_obj_set_y(ui_Container36, 99);
    lv_obj_set_align(ui_Container36, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container36, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Container36, &ui_img_airflow_small_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container39 = lv_obj_create(ui_Container33);
    lv_obj_remove_style_all(ui_Container39);
    lv_obj_set_width(ui_Container39, 50);
    lv_obj_set_height(ui_Container39, 50);
    lv_obj_set_x(ui_Container39, 0);
    lv_obj_set_y(ui_Container39, 97);
    lv_obj_set_align(ui_Container39, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container39, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Container39, &ui_img_airflow_middle_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Container39, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container40 = lv_obj_create(ui_Container33);
    lv_obj_remove_style_all(ui_Container40);
    lv_obj_set_width(ui_Container40, 60);
    lv_obj_set_height(ui_Container40, 60);
    lv_obj_set_x(ui_Container40, 160);
    lv_obj_set_y(ui_Container40, 95);
    lv_obj_set_align(ui_Container40, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container40, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Container40, &ui_img_airflow_large_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Container40, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container35 = lv_obj_create(ui_Container48);
    lv_obj_remove_style_all(ui_Container35);
    lv_obj_set_width(ui_Container35, 80);
    lv_obj_set_height(ui_Container35, 80);
    lv_obj_set_x(ui_Container35, -260);
    lv_obj_set_y(ui_Container35, 0);
    lv_obj_set_align(ui_Container35, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container35, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container35, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Container35, &ui_img_decrease_white_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container35, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container35, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container37 = lv_obj_create(ui_Container48);
    lv_obj_remove_style_all(ui_Container37);
    lv_obj_set_width(ui_Container37, 80);
    lv_obj_set_height(ui_Container37, 80);
    lv_obj_set_x(ui_Container37, 260);
    lv_obj_set_y(ui_Container37, 0);
    lv_obj_set_align(ui_Container37, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container37, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container37, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Container37, &ui_img_increase_white_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container37, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container37, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Container48);
    lv_obj_set_width(ui_Switch1, 100);
    lv_obj_set_height(ui_Switch1, 50);
    lv_obj_set_x(ui_Switch1, -200);
    lv_obj_set_y(ui_Switch1, 160);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Switch1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Container48);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -100);
    lv_obj_set_y(ui_Label18, 160);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "自动");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &ui_font_simhei46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch3 = lv_switch_create(ui_Container48);
    lv_obj_set_width(ui_Switch3, 100);
    lv_obj_set_height(ui_Switch3, 50);
    lv_obj_set_x(ui_Switch3, 80);
    lv_obj_set_y(ui_Switch3, 160);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Switch3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_Container48);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 180);
    lv_obj_set_y(ui_Label27, 160);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "静音");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &ui_font_simhei46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container58 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container58);
    lv_obj_set_width(ui_Container58, 640);
    lv_obj_set_height(ui_Container58, 420);
    lv_obj_set_x(ui_Container58, 0);
    lv_obj_set_y(ui_Container58, 130);
    lv_obj_set_align(ui_Container58, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Container58, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Container58, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label26 = lv_label_create(ui_Container58);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "暂无风向控制功能");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label26, &ui_font_simhei46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container46 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container46);
    lv_obj_set_width(ui_Container46, 640);
    lv_obj_set_height(ui_Container46, 420);
    lv_obj_set_x(ui_Container46, 0);
    lv_obj_set_y(ui_Container46, 115);
    lv_obj_set_align(ui_Container46, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Container46, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Container46, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container41 = lv_obj_create(ui_Container46);
    lv_obj_remove_style_all(ui_Container41);
    lv_obj_set_width(ui_Container41, 200);
    lv_obj_set_height(ui_Container41, 60);
    lv_obj_set_x(ui_Container41, -50);
    lv_obj_set_y(ui_Container41, -140);
    lv_obj_set_align(ui_Container41, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container41, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container41, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container41, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Container41);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "重置");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label28, &ui_font_simhei46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container47 = lv_obj_create(ui_Container46);
    lv_obj_remove_style_all(ui_Container47);
    lv_obj_set_width(ui_Container47, 200);
    lv_obj_set_height(ui_Container47, 50);
    lv_obj_set_x(ui_Container47, -50);
    lv_obj_set_y(ui_Container47, -50);
    lv_obj_set_align(ui_Container47, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container47, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container47, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container47, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Container47);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "00:00");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label29, &ui_font_simhei36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_Container46);
    lv_obj_set_width(ui_Switch2, 100);
    lv_obj_set_height(ui_Switch2, 50);
    lv_obj_set_x(ui_Switch2, 120);
    lv_obj_set_y(ui_Switch2, -50);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Switch2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container50 = lv_obj_create(ui_Container46);
    lv_obj_remove_style_all(ui_Container50);
    lv_obj_set_width(ui_Container50, 200);
    lv_obj_set_height(ui_Container50, 50);
    lv_obj_set_x(ui_Container50, -50);
    lv_obj_set_y(ui_Container50, 20);
    lv_obj_set_align(ui_Container50, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container50, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container50, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container50, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Container50);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "00:00");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label31, &ui_font_simhei36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch5 = lv_switch_create(ui_Container46);
    lv_obj_set_width(ui_Switch5, 100);
    lv_obj_set_height(ui_Switch5, 50);
    lv_obj_set_x(ui_Switch5, 120);
    lv_obj_set_y(ui_Switch5, 20);
    lv_obj_set_align(ui_Switch5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch5, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Switch5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container20 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container20);
    lv_obj_set_width(ui_Container20, 600);
    lv_obj_set_height(ui_Container20, 100);
    lv_obj_set_x(ui_Container20, 0);
    lv_obj_set_y(ui_Container20, 260);
    lv_obj_set_align(ui_Container20, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container15 = lv_obj_create(ui_Container20);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, 72);
    lv_obj_set_height(ui_Container15, 85);
    lv_obj_set_x(ui_Container15, -216);
    lv_obj_set_y(ui_Container15, 0);
    lv_obj_set_align(ui_Container15, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image17 = lv_image_create(ui_Container15);
    lv_image_set_src(ui_Image17, &ui_img_mode_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image17, 0);
    lv_obj_set_y(ui_Image17, -10);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Container15);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 0);
    lv_obj_set_y(ui_Label17, 30);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "模式");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_simhei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container16 = lv_obj_create(ui_Container20);
    lv_obj_remove_style_all(ui_Container16);
    lv_obj_set_width(ui_Container16, 72);
    lv_obj_set_height(ui_Container16, 85);
    lv_obj_set_x(ui_Container16, -72);
    lv_obj_set_y(ui_Container16, 0);
    lv_obj_set_align(ui_Container16, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_image_create(ui_Container16);
    lv_image_set_src(ui_Image8, &ui_img_airflow_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, 0);
    lv_obj_set_y(ui_Image8, -10);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_Container16);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, 30);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "风量");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_simhei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container17 = lv_obj_create(ui_Container20);
    lv_obj_remove_style_all(ui_Container17);
    lv_obj_set_width(ui_Container17, 72);
    lv_obj_set_height(ui_Container17, 85);
    lv_obj_set_x(ui_Container17, 72);
    lv_obj_set_y(ui_Container17, 0);
    lv_obj_set_align(ui_Container17, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_image_create(ui_Container17);
    lv_image_set_src(ui_Image14, &ui_img_wind_direction_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image14, 0);
    lv_obj_set_y(ui_Image14, -10);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_Container17);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 0);
    lv_obj_set_y(ui_Label13, 30);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "风向");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_simhei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container18 = lv_obj_create(ui_Container20);
    lv_obj_remove_style_all(ui_Container18);
    lv_obj_set_width(ui_Container18, 72);
    lv_obj_set_height(ui_Container18, 85);
    lv_obj_set_x(ui_Container18, 216);
    lv_obj_set_y(ui_Container18, 0);
    lv_obj_set_align(ui_Container18, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image15 = lv_image_create(ui_Container18);
    lv_image_set_src(ui_Image15, &ui_img_settings_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image15, 0);
    lv_obj_set_y(ui_Image15, -10);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_Container18);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 0);
    lv_obj_set_y(ui_Label15, 30);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "设置");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_simhei24, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Container13 = NULL;
    ui_Label14 = NULL;
    ui_Image12 = NULL;
    ui_Container14 = NULL;
    ui_Image13 = NULL;
    ui_Container19 = NULL;
    ui_Container21 = NULL;
    ui_Image16 = NULL;
    ui_Label16 = NULL;
    ui_Container23 = NULL;
    ui_Image19 = NULL;
    ui_Label19 = NULL;
    ui_Container24 = NULL;
    ui_Image20 = NULL;
    ui_Label20 = NULL;
    ui_Container28 = NULL;
    ui_Container25 = NULL;
    ui_Label21 = NULL;
    ui_Container26 = NULL;
    ui_Container22 = NULL;
    ui_Label22 = NULL;
    ui_Container30 = NULL;
    ui_Container27 = NULL;
    ui_Label23 = NULL;
    ui_Container32 = NULL;
    ui_Container29 = NULL;
    ui_Label24 = NULL;
    ui_Container34 = NULL;
    ui_Container31 = NULL;
    ui_Label25 = NULL;
    ui_Container48 = NULL;
    ui_Container33 = NULL;
    ui_Container38 = NULL;
    ui_Container42 = NULL;
    ui_Container43 = NULL;
    ui_Container44 = NULL;
    ui_Container45 = NULL;
    ui_Container36 = NULL;
    ui_Container39 = NULL;
    ui_Container40 = NULL;
    ui_Container35 = NULL;
    ui_Container37 = NULL;
    ui_Switch1 = NULL;
    ui_Label18 = NULL;
    ui_Switch3 = NULL;
    ui_Label27 = NULL;
    ui_Container58 = NULL;
    ui_Label26 = NULL;
    ui_Container46 = NULL;
    ui_Container41 = NULL;
    ui_Label28 = NULL;
    ui_Container47 = NULL;
    ui_Label29 = NULL;
    ui_Switch2 = NULL;
    ui_Container50 = NULL;
    ui_Label31 = NULL;
    ui_Switch5 = NULL;
    ui_Container20 = NULL;
    ui_Container15 = NULL;
    ui_Image17 = NULL;
    ui_Label17 = NULL;
    ui_Container16 = NULL;
    ui_Image8 = NULL;
    ui_Label9 = NULL;
    ui_Container17 = NULL;
    ui_Image14 = NULL;
    ui_Label13 = NULL;
    ui_Container18 = NULL;
    ui_Image15 = NULL;
    ui_Label15 = NULL;

}
