// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: waveshare

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Label12;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

