// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: waveshare

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Container19;
extern lv_obj_t * ui_Container21;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Container23;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Container24;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Container28;
extern lv_obj_t * ui_Container25;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Container26;
extern lv_obj_t * ui_Container22;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Container30;
extern lv_obj_t * ui_Container27;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Container32;
extern lv_obj_t * ui_Container29;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Container34;
extern lv_obj_t * ui_Container31;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Container48;
extern lv_obj_t * ui_Container33;
extern lv_obj_t * ui_Container38;
extern lv_obj_t * ui_Container42;
extern lv_obj_t * ui_Container43;
extern lv_obj_t * ui_Container44;
extern lv_obj_t * ui_Container45;
extern lv_obj_t * ui_Container36;
extern lv_obj_t * ui_Container39;
extern lv_obj_t * ui_Container40;
extern lv_obj_t * ui_Container35;
extern lv_obj_t * ui_Container37;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Container58;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Container46;
extern lv_obj_t * ui_Container41;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Container47;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Container50;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Switch5;
extern lv_obj_t * ui_Container20;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Container17;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Container18;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Label15;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

